### ISSUE TITLE
Something wrong with pyffx.Integer

### ISSUE THREAD

**Issue by Milou314** [emulbreh/pyffx#1]
This:

```
import pyffx

print "Integer:"
e = pyffx.Integer(b'encrypt')
val = 12345678
print val
enc = e.encrypt(val)
print enc
dec = e.decrypt(enc)
print dec
print
```
results in:
```
Integer:
12345678
3853168
7841194
```

So: What's wrong with this? Even longer keys sometimes work and sometimes fail?!

**Comment by Milou314** [comment]
Ok, meanwhile I added some print commands to the souce code. The problem with integer encryptions is, that there is a leading zero

"03853168"

since in the library the integer is converted to string and than encrypted with alphabet "01234656789".
Unfortunately there is no workaround for this because only the integer is given back but no additional information. The user has to check, whether the encryption has the same length as the original or not, keep this in mind and add the leading zero before decrytion (how???). Another workaround would be to remove the "0" from the alphabet. Finally all integer could be converted to string before encryption. Another solution could be to tell pyffx the maximum length of an integer, i.e. 
`e = pyffx.Integer(b'encrypt',digits=10)`
Internally too short values could be enhanced by leading zeros.

**Comment by Milou314** [comment]
So I finally changed the file "codecs.py" like this:
```
class Integer(String):
    def __init__(self, ffx, **kwargs):
        try:
            digits = kwargs['digits']        
            self.digits = digits
            del kwargs['digits'] 
        except:
            print
            print "pyffx.Integer usage: pyffx.Integer(key,digits=val)"
            raise
        super(Integer, self).__init__(ffx, string.digits, **kwargs)

    def pack(self, v):        
        vString = str(v)
        zeros   = self.digits-len(vString)
        if zeros<0:
            print
            print "pyffx.Integer: value '%s' longer than %i digits ..." % (vString,self.digits)
            raise        
        vString = zeros*'0'+vString
        return super(Integer, self).pack(vString)

    def unpack(self, v, t):        
        return int(super(Integer, self).unpack(v, t))
```
Now it's working:
```
import pyffx

print "Integer:"
e = pyffx.Integer(b'encrypt',digits=10)
val = 12345678
print val
enc = e.encrypt(val)
print enc
dec = e.decrypt(enc)
print dec
print
```
results in 
```
Integer:
12345678
8706078674
12345678
```

**Comment by emulbreh** [comment]
Thanks for the report! I simply made `length` required for all codecs since it's unclear how padding should even work for non-integers. Please reopen if this change doesn't solve your issue.
