### ISSUE TITLE
how can I exlude the combination of \n and \r characters in the encrypted result?

### ISSUE THREAD

**Issue by Radu3000** [emulbreh/pyffx#8]
It is ok if my encrypted result has "]" and "n" separately.  But that creates problems during rendering in java and python - new lines and other ...

Can I prevent the encrypted results to produce the following sequence of chars?
"\n" and "\r"

Thanks,
Radu

**Comment by emulbreh** [comment]
There's nothing built into pyffx that would help, but there's probably a way to implement this restriction on top of it.

If you don't need to preserve the length of the output you could try to escape the sequences you don't want (e.g. replace "\n" -> "\n0" and "0" -> "00").

Alternatively, you could also try to come up with a scheme that uses a bigger alphabet, e.g. 
```python
safe_chars = set(string.printable)
alphabet = (chars - {'\n'}) | {f'\n{c}' for c in chars - {'\r'}}
 ```
If the length of the string is odd you need to treat the last char specially or pad the string.

**Comment by emulbreh** [comment]
I'm closing this issue for now. Feel free to to open a PR if there's something unversally useful you'd like to add to pyffx. Regarding your actual problem, stackoverflow might be a better place to ask for an encoding scheme.
