### ISSUE TITLE
Are there guaranteed to be no collisions when using hashlib.sha1?

### ISSUE THREAD

**Issue by pjdon** [emulbreh/pyffx#9]
I'm still not sure exactly how the library works, but if it uses `hashlib.sha1`, is there an very small chance of a collision, or a zero chance?

**Comment by emulbreh** [comment]
The hash function is only used in an HMAC-based stream cipher construction. Modulo bugs, the encryption should be a bijection, i.e. not have collisions.

**Comment by pjdon** [comment]
Excellent, thanks for clarifying!
